apiVersion: v1
kind: Service
metadata:
  labels:
    name: game-monitor
  name: game-monitor
  namespace: grafana
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    name: game-monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-monitor
  namespace: grafana
  labels:
    app: game-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: game-monitor
  template:
    metadata:
      labels:
        name: game-monitor
    spec:
      restartPolicy: Always
      containers:
      - image: game-monitor-img
        imagePullPolicy: IfNotPresent
        name: game-monitor
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
