apiVersion: v1
kind: Service
metadata:
  labels:
    name: game-monitor
  name: game-monitor
  namespace: grafana
spec:
  ports:
  - name: http
    port: 8123
    targetPort: 8123
  selector:
    name: game-monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-monitor
  namespace: grafana
  labels:
    app: game-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: game-monitor
  template:
    metadata:
      labels:
        name: game-monitor
    spec:
      containers:
      - image: 083250277353.dkr.ecr.ap-northeast-1.amazonaws.com/game-monitor:v${VERSION}
        imagePullPolicy: IfNotPresent
        name: game-monitor
        env:
          - name: OTEL_HTTP_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: OTEL_HTTP_PORT
            value: "4318"
        ports:
        - containerPort: 8123
          hostPort: 8123
          name: http
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
